### ISSUE TITLE
Why not wifi

### ISSUE THREAD

**Issue by nickrout** [UbhiTS/ad-autointernetrebooter#1]
Why does this not work with wifi switches. My modem is not my AP nor is it my DHCP server.

**Comment by UbhiTS** [comment]
theoretically if you only have your modem on the switch/socket then it might work (need someone to test and confirm that). The trouble is if you have your router on the switch/socket too. Normally people have a modem/router combo and I didn't want users of the app complaining that it's not working. Because the moment you turn off your router, HA will lose the connection to the switch and cannot turn it back on !!!

**Comment by nickrout** [comment]
I gave up using the AP and routing aspects of my ISP supplied device soon after I bought it. So I think it will work.

**Comment by UbhiTS** [comment]
can you please try and let me know. If it works for you I'll close this issue :)

**Comment by nickrout** [comment]
Yes it works as long as you don't switch off a whatever links the switch and your ha machine.

**Comment by UbhiTS** [comment]
awesome, closing this issue!
